### ISSUE TITLE
Scala.js testing framework support

### ISSUE THREAD

**Issue by rtimush** [lihaoyi/mill#102]
Tests for ScalaJSModule should be executed with JavaScript engine. We probably don't need to support all JavaScript engines available in SBT, but having DOM support looks like a necessity.

**Comment by lihaoyi** [comment]
I think hardcoding support for Node.js would be a good first start

**Comment by sjrd** [comment]
If you reuse the `JSEnv` API that ships in [the `scalajs-env` artifact](https://www.scala-js.org/api/scalajs-js-envs/1.0.0-M2/org/scalajs/jsenv/index.html) that we publish, you can immediately use all the same JS engines that sbt-scalajs supports.

Even better, since you seem to be using the `sbt.testing._` API to run tests on the JVM, you can directly reuse our [test adapter](https://www.scala-js.org/api/scalajs-sbt-test-adapter/1.0.0-M2/org/scalajs/testadapter/TestAdapter.html), which exposes testing frameworks from the JS side as `sbt.testing.Framework`s on the JVM side. You simply have to instantiate the `TestAdapter` class with a `ComJSEnv`, and then call its `loadFrameworks` method to get a list of `sbt.testing.Framework`s.
