### ISSUE TITLE
Deps resolution can contain multiple versions of the same library

### ISSUE THREAD

**Issue by rockjam** [lihaoyi/mill#123]
When dependency resolution happens in two or more targets, results of those are concatenated together, there is a risk of getting multiple version of the same artifact. Here is minimal reproducable `build.sc`: 

```
import mill._
import mill.scalalib._

object reproduce extends ScalaModule {
  def scalaVersion = "2.12.4"


  def evicted = T{
    val result = resolveDeps(resolveOne)()
    result.foreach(println)
    result
  }

  def notEvicted = T{
    val result = resolveDeps(resolveTwo)() ++ resolveDeps(resolveThree)()
    result.foreach(println)
    result
  }

  def resolveOne = T {
    Agg(
      ivy"com.lihaoyi::utest:0.6.0",
      ivy"com.lihaoyi::utest:0.6.1",
    )
  }

  def resolveTwo = T {
    Agg(
      ivy"com.lihaoyi::utest:0.6.0"
    )
  }

  def resolveThree = T {
    Agg(
      ivy"com.lihaoyi::utest:0.6.1"
    )
  }
}
```

`mill reproduce.evicted` will print out one version of utest, whereas  `mill reproduce.notEvicted` will print out two versions on utest

**Comment by lihaoyi** [comment]
We could "fix" this by aggregating third-party `Dep`s and doing a big coursier resolution per-module, whereas we currently run a small coursier resolution per-module and aggregate the jars (which can have dupes).

Not sure if it's better or worse; in the end someone's jar is going to be stomped over, but I guess if coursier does the stomping it'll pick the highest version rather than just picking arbitrarily based on ordering

**Comment by lihaoyi** [comment]
This should be fixed in master, SBT style (we aggregate all ivyDeps until the last minute when we resolve them before compiling/execution)
