### ISSUE TITLE
Using hyphen inside module names

### ISSUE THREAD

**Issue by AlexITC** [lihaoyi/mill#166]
At the moment, it seems to be no way to include hyphens in the module names which is a common practice to name sbt modules, for example, I create the folder `playsonify-test` and then, define it in the build definition as `object playsonify-test extends ...` or using backtics around the name with no luck.

It would be useful to be able to do this.

**Comment by ajrnz** [comment]
As a workaround for the moment you can do something like

```scala
object MyModule extends ScalaModule {
  def millSourcePath = super.millSourcePath / up / "my-module"
...
```

it seems to work at least in simple cases

**Comment by AlexITC** [comment]
Where does the `up` comes from? if I don't import it I get an error.

Also, if I understand correctly, the drawback would be that while publishing the library, the artifact would use `mymodule` instead of `my-module`.

**Comment by ajrnz** [comment]
Use `import ammonite.ops._`

Yep. It's by no means perfect but it might get you compiling.

**Comment by francisdb** [comment]
you could also use this to avoid the ammonite ops import

```scala
object MyModule extends ScalaModule {
  def millSourcePath = build.millSourcePath / "my-module"
...
```

**Comment by ssokolenko** [comment]
I think the "hyphen inside module" is actually the part of a wider issue, you can't use scala's backticks to wrap any task/module/target names with special symbols, only "a-zA-Z0-9_" are allowed by argument parser. 

Also, while it is possible to define a task with special symbols like "say-^hello" - it will be resolved as "say$minus$uphello" but you wont' be able to call it since as noted above the mill's arg parser only accepts "a-zA-Z0-9_" for selectors.
Putting special chars into module names makes them not being discovered by mill at all.

So, the issue should either be fixed in a way to support scala syntax for module/task/target names (i.e. backticked names with special chars) or explicitly restricted by the mill at compile time + related documentation.

**Comment by lihaoyi** [comment]
the CLI interface will never support backticks, because bash uses backticks for something else (I forgot what), but we can easily make it support things like `foo.bar-baz.qux`. The only trade-off is if in future we want to extend our query language to support negation, where you can do `mill "foo._ - foo.baz` to exclude `foo.baz` from the `foo._` query, we need to make sure it's both un-ambiguous and not confusing.

For now, overriding `millSourcePath` seems like a reasonable stopgap solution

**Comment by Krever** [comment]
This also affects `mill.scalalib.GenIdeaModule/idea`.

**Comment by jkstrauss** [comment]
@lihaoyi I believe that the @ssokolenko wants to allow back-ticks in the script code, not at the CLI. 

That being said, I think that it is quite reasonable to use a hyphen in a target name; subtraction, even if implemented, should probably only work with spaces between the identifiers.

I have been able to implement it with only a few lines of code, but I was wondering if you have an opinion about other characters, since you have to make a lookup table for each supported character to convert between the actual Java name and scala name, e.g. $minus -> -, $amp -> &, etc.



BTW, back-ticks are used by bash to return the results of a subshell.

**Comment by ssokolenko** [comment]
@jkstrauss you got me right, I think it would be nice to have back ticks to work in the build scripts, not at the CLI. Thanks for noticing this!

**Comment by rockjam** [comment]
Closed by https://github.com/lihaoyi/mill/pull/362
