### ISSUE TITLE
brew install mill should not depend on java8

### ISSUE THREAD

**Issue by megri** [lihaoyi/mill#220]
I use [sdkman](http://sdkman.io/) to manage my java installations but mill requires a brew version of java to be installed: https://github.com/Homebrew/homebrew-core/blob/374e70653a865dc08781dd6244c2a925206bc931/Formula/mill.rb#L9

Simply removing this line should allow it to work with sdkman, but may introduce other bugs if no java8-version is available. A shell-check like `$("$JAVA_HOME/bin/java" -version 2>&1 | awk -F '"' '/version/ {print $2}')` can be performed to validate the java version, but I'm not sure how to do this from Ruby

**Comment by benjaminfrank** [comment]
I think homebrew uses `/usr/libexec/java_home` to figure out if a suitable java installation is present:
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/language/java.rb#L5
and only warns/installs the homebrew version if it can't find one. not sure how that check interacts with sdkman installations though.
using a manual check instead of the homebrew provided one sounds even more brittle to me. but maybe we'd could to ask over at homebrew how they think this issue should be handled?

**Comment by megri** [comment]
Hmm, interesting. Could be that sdkman doesn't integrate with `/usr/libexec/java_home`, or that something is wonky with my OS installation: when I run it I get null.

I agree with your assessment; using the java_home executable should be the best approach, it's just that it's not working in my case. I'll see if I can find a reason :)

**Comment by megri** [comment]
I'll close this issue as it seems most tools require that /usr/libexec/java_home returns a valid value.
