### ISSUE TITLE
Parallel Task Evaluation

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/mill#32]
The current `Evaluator` is sequential: tasks are evaluated one by one in a linear topological order.

Because we have the dependency graph between tasks, it should be straightforward to implement a parallel evaluator that evaluates tasks N-ways parallel. This would not require any change to the user-code implementing tasks and targets.

Open questions include how such a parallel evaluator will fit into the existing codebase (we probably want to keep the sequential evaluator around as an option indefinitely) and how to make sense of the interleaved log-spam from the parallel-executing tasks (we could provide a `T.ctx().println` method that will prefix the stdout with the name of the target being evaluated, and ask task writers to use that)

**Comment by mdedetrich** [comment]
> Yeah this is a hard problem. We can't guarantee that tasks are well-behaved, but we can give them resource guidelines as-you-say that, if followed, would avoid overloading the host system. Some things will always be fuzzy as long as we are running in-process, e.g. memory usage is untrackable, but that's no worse than SBT.

To satisfy this problem, you can supply hints to certain tasks about how many cores they can use so they behave greedily. I agree that generally this is a difficult problem, its actually one of the things that `ExecutionContext` in `Future` is designed to solve, i.e assuming we have a machine with 4 cores

*  for a chain of computations that represent the "compile" task for Scalac, I wan't to supply an `ExecutionContext` that consists of 2 cores, since compiling by scalac is extremely CPU bound
* for all other styles of chain of computations, I can supply an `ExecutionContext` which contains a ForkJoinPool backed by 2 cores (since its a `ForkJoinPool` it will also implement fairness so to make sure that other computations by the same `ExecutionContext` don't steal too much time). This is generally what you want for IO bound tasks, i.e. what is typical of webservers

Note that I am not advocating for `Future` here, this is just an explanation of how to approach this problem. It seems like this project has created its own version of `Task`, but I know there are other implementations of `Task` (i.e. Monix `Task`) which should also allow for this type of fine grained behavior, i.e. see https://monix.io/docs/2x/execution/scheduler.html#execution-model (with monix task you can set a task to always be synchronous, which means is good for CPU bound tasks)

**Comment by francisdb** [comment]
What is the priority on this? Currently mill is unusable for bigger projects because of at least 4x compile time increase compared to sbt.

**Comment by mdedetrich** [comment]
@francisdb Honestly as stated earlier, you would probably need to replace mill's `Task` with something else, I recommend Monix only because its got the most sensible out of the box defaults (i.e. its optimized for both CPU and IO bound tasks by using a batching mechanism). `Future` is by default optimized for IO bound tasks where as tasks such as Scalaz8/Cats IO are optimized by default for CPU bound tasks.

Its not a trivial task, of course you can probably modify Mill's own Task with all of the required functionality, but you would probably be recreating yet another Task type (although there are merits to this, i.e. not bringing in large dependencies like Cats or Scalaz)

**Comment by lihaoyi** [comment]
Mill's task is a free-applicative and it should be possible to do this without touching the `mill.Task` type at all; all the core changes for parallelism should take place in the `Evaluator`.

Whether the new "`ParallelEvaluator`" uses Future or Monix or Scalaz or Cats for it's parallelization logic is an internal implementation detail. If we need to tag our `mill.Task`s with some metadata to allow a `ParallelEvaluator` to schedule more effectively, we can easily do so without invasively replacing the core type.

**Comment by mdedetrich** [comment]
Okay, I will try and use Monix Task as the underlying execution engine without changing `mill.Task`, theoretically it should be fine but I guess we will find out

**Comment by hepin1989** [comment]
@mdedetrich I think put a stream/action/queue layer before the execution layer is more approachable. By leaving it before the underlying effect system. Then we could make the slow path more explicit, and give us more space for more optimization like fusing multiply action as a single batch operation to the same target(folder), which would help for the disk/SSD.

 In my code, not a building system, we have AST -> AST with Task -> Interpreter ->Reactive-Stream based execution.

**Comment by hepin1989** [comment]
@mdedetrich So I think there is no need to change the `mill.Task`, it's okay and carries metadata, Scalaz or Monix or another layer with ReactiveStream implement is both ok.I more like the last one. Once we lift the actions, we could do batching and fusing multi single-actions to the same data source as a batch operation(both read or write).

**Comment by lefou** [comment]
Has anybody started to implement this?

**Comment by lefou** [comment]
As I already implemented parallel execution of tasks in SBuild, I will look into it. Can't promise anything, I have to get familiar with the code base first.

**Comment by lefou** [comment]
I created PR #480 implementing parallel task evaluation, but to my surprise, nobody tested/commented on it.

**Comment by lihaoyi** [comment]
@lefou not surprising to me at all; the evaluator code is relatively gnarly, and sufficiently well encapsulated that nobody would learn about it just from using Mill. Even I myself am somewhat rusty, and probably will have to re-learn large portions of the logic to properly review it. I unfortunately don't have time to help iterate on it with you, and improving Mill's performance via parallelism isn't currently a requirement for any of my own work.

If you'd like to push it forward, once you're happy with it and it's in a somewhat merge-able state (no conflicts, tests passing) I can put in the time to give it a proper review. I understand that it's a non-trivial amount of work, but that's probably unavoidable given the invasive nature of this change, the fundamentally complex domain we're working in (this isn't just some CRUD web app), and the desire to maintain rough compatibility with all the surrounding code in the Mill repo (external code isn't likely to be affected).

**Comment by lefou** [comment]
I guess, what I'm missing is, that at least someone tried to build something with that branch. The code review itself is only the finish afterwards. The point is, rebasing that branch is very cumbersome, at least with the (unwritten, inferred by me) no-merge-commit rule. And some part of me hesitates to squash everything into one commit. The motivation to update the branch is currently extrinsic.

**Comment by lihaoyi** [comment]
I don't have any issues with merges or squashes; I typically merge master into branches and then squash the entire PR into a single commit when merging the branch into master. If rebasing is too much of a hassle, feel free to not.

**Comment by nafg** [comment]
What's the status of this

**Comment by lefou** [comment]
@nafg #480 Is an implementation of it and ready for testing. More details are in the PR, too.

**Comment by lefou** [comment]
Hi all, let me give you an update of the situation.

My PR #480 is now in a state that it works very well for all projects that I'm aware of. I'm currently polishing it a bit before we merge it into the master branch, so that you can start to consume it. You can also expect a new tagged release very soon.

The journey isn't over, though. Parallelism is still experimental and must be enabled manually with `--jobs n`, where `n` is the thread count.The implementation also needs some refactoring. And we probably want more polishing, e.g. how the `clean` task and the `all` task should behave. Any feedback is much appreciated.

**Comment by lefou** [comment]
Closed via #480.

**Comment by lefou** [comment]
You can grab it as mill `0.6.1-120-8d6b23`.
