### ISSUE TITLE
`mill version` fails if buildfile can't be compiled

### ISSUE THREAD

**Issue by lefou** [lihaoyi/mill#520]
Reproduce with the following example:

```
$ echo "ERROR" >> build.sc
$ mill -i version
Compiling /tmp/test/build.sc
build.sc:249: not found: value ERROR
val res_14 = ERROR
             ^
Compilation Failed
$ echo $?
1
```

Of course, the upper example is trivial and easy to fix. In real life if might be more difficult. E.g. if the buildfile fails because of an mill API change, one might want to use `mill version` to check which version is used, but that wouldn't work.

**Comment by lihaoyi** [comment]
As part of https://github.com/lihaoyi/mill/issues/502, we might make it possible to annotated certain entrypoint functions as not depending on the build file. I suspect we may have more of these in future, and it would be nice to be able to write them as a straightforward scala function rather than shoving more logic into the already-pretty-messy arg-parsing-and-initialization logic

**Comment by lefou** [comment]
There is now an alternative: `mill --version`
