### ISSUE TITLE
Inconsistent documentation version

### ISSUE THREAD

**Issue by uosis** [lihaoyi/mill#667]
It looks like documentation hosted at http://www.lihaoyi.com/mill/ points to master branch, while talking about last released version in the installation section.

This creates confusion when trying to use features that are in documentation, but not yet released.

I was trying to use bloop integration, and it took quite a bit of investigation to figure out why $MILL_VERSION interpolation (#649) isn't working as documented...

It's not a huge issue, but it would be nice if documentation matched the last released version.

**Comment by lefou** [comment]
You are right, documentation always reflects master branch.

**Comment by lihaoyi-databricks** [comment]
I think for now I'd like to maintain the documentation as reflecting master; to mitigate this issue, we can simply tag a release more frequently, so the lag will be O(days) rather than O(months).

The alternative would be to have the documentation always reflect the last tagged release, but then adding to or improving the documentation would suffer long delays. The solution for *that* problem would be to tag releases more frequently as well, but if we're going to be tagging frequent releases then we can just keep the docs on master to begin with

**Comment by lefou** [comment]
We could add a comment in the footer of the page, that the documentation reflects the master branch, possibly even the concrete sub-version.

**Comment by lefou** [comment]
Added that note to generated documentation.
