### ISSUE TITLE
Using val in Task

### ISSUE THREAD

**Issue by sequencer** [lihaoyi/mill#788]
Here is my demo code
```
import mill._
object test extends Module{
  def task1(str: String) = T.task{
    str.toUpperCase
  }
  def task2 = T {
    val a = "a"
    task1(a)()
  }
}
```
There is no circular dependency, but a error raises:
```
build.sc:8: Target#apply() call cannot use `value a` defined within the T{...} block
    task1(a)()
          ^
build.sc:6: `T.command` definitions must have 1 parameter list
  def task2 = T {
      ^
Compilation Failed
```
I don't know if this is a expected behavior.

**Comment by lefou** [comment]
That is expected behavior. Although, we could improve the error message. Why it speaks about `T.command` isn't clear at all.

The reason is inputs were calculate before the depending target. That's why you can't define the parameter in the target, it's simply to late.

It should work if you move the constant `a` out of the target. Make it a outer val, or a parameter of your def (if you want a command). For variable input, you can provide it via an additional target.
