### ISSUE TITLE
Make cmdline options for mill-server mode and repl more clear

### ISSUE THREAD

**Issue by lefou** [lihaoyi/mill#926]
We see confusion about the `-i` option quite a lot in Gitter channel and also advise to use `-i` very often when things don't work as expected.

I propose to deprecate the current `-i`, `--interactive` option in favour of two new options:

* `--repl` - Starts a interactive mill session and will implicitly not use the mill server (same as old `--interactive`)
* `--server 0|false|off|no` or `--no-server` - Starts mill without using a server process
* `--server 1|true|on|yes` - Starts mill with a background server process

**Comment by hypatian** [comment]
I'd suggest that while server-related switches are being considered, a switch to force the server to restart or to stop should be added.

There will continue to be things that are frozen at server start time or build init time (whether unintentionally or because there's simply no other choice at the moment.) Not needing to find and kill the old server by hand would be a pleasant improvement.

**Comment by hypatian** [comment]
Looking at this a bit right now. From what I can see, the reason `-i` is so fundamental (has to be the first argument, etc.) comes from way back in fd8a2567ad32c11bcf8adbaca85bdba72bb4f935.

When `-i` isn't used, it starts `MillClientMain` which is Java code and starts faster and then spawns off a separate process for the server which loads up Scala. And then if you _do_ use `-i`, it starts `mill.MillMain` which brings in the Scala libraries and is a bit slower.

`MillClientMain` currently doesn't interpret its arguments at all--it just shoves them all over to the server for handling.

Because of all of this it might be easiest to keep this as simple as possible, so it can be done in the launcher script without too much trouble.  So I'm going to suggest:

* `--repl` - Starts a interactive mill session and will implicitly not use the mill server (same as old `--interactive` with no target), and complains if a target is given.
* `--no-server` - Starts mill without using a server process (same as old `--interactive` with a target), and complains if no target is given.
* `--interactive` - Same as the current behavior for compatibility, `-i` does this. Maybe have this produce a warning that its behavior will be the same as `--no-server` at some point in the future.

All of these arguments are very simple (presence or absence), and can be restricted to "must be the very first argument". That makes them easy to handle with the current launcher script.

**Comment by hypatian** [comment]
I just tossed up #927 as a first pass at doing this. It does what I suggested in my last comment.

**Comment by lefou** [comment]
Merged right now. Thank you very much!
